id: b68512b03fa94d2a8026453e1601571a
initial_creation_type: ocr
source_metadata:
  volumes:
    b0ee3e74a1664d2c8ca9c2b1e6ef8865:
      base_file: v075.txt
      image_group_id: I1PD95921
      title: ''
      total_pages: 1774
      volume_number: 76
