id: D2C481816
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:41:42+00:00'
last_modified: '2022-05-29T08:25:12.795561+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d7db:
      image_group_id: I1PD95921
      title: ཐེག་པ་ཆེན་པོ་བསྡུས་པའི་འགྲེལ་པ།
      total_pages: 1774
      order: 76
      base_file: d7db.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
